Dev/dmotor/optimize hash
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #192
Opened 2021-04-18 23:08 UTC by DMotorygin

PURPOSE: Remove routines that waste performance

TECHNICAL DETAILS: We have some calls that are doing no useful work but waste performance. They are leftovers from old codes that we haven't removed yet.

2021-04-19 08:47 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderObjects.cpp
> +		hash << 0; // dagPath.inclusiveMatrix();
Looks like unnecessary line of code

2021-04-19 08:48 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderObjects.cpp
> +		hash << 0; // dagPath.inclusiveMatrix();
If inclusive matrix call is about to be removed isVisible call is also unnecessary

2021-05-05 07:28 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderObjects.cpp
>  {
please add a flag if calculate hash or not instead of accessing context fields here

2021-05-05 07:29 UTC, Vsevolod1983 requested changes

2021-05-05 07:29 UTC, Vsevolod1983 commented on FireRender.Maya.Src/Context/FireRenderContext.cpp
> +			MString objname = dagNode.name();
please remove if unysed

2021-05-05 07:29 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderObjects.cpp
> +	MString name = dagPath.fullPathName();
please remove if unused

2021-05-06 08:21 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderViewport.cpp
> -			else //Standalone render view (hypershade only?)
why this part was removed ?

2021-05-06 08:21 UTC, Vsevolod1983 approved these changes

2021-05-12 03:27 UTC, bsavery commented
Don't merge?

2021-05-12 18:00 UTC, merged