Volumes density lookup
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #242
Opened 2021-09-07 09:26 UTC by V-Gorash

JIRA TICKET: RPRMAYA-2895, RPRMAYA-2878

EFFECT OF CHANGES: 
        VDB volumes: density multiplier enabled, random crash fix
        Maya volumes: density displays correctly

NOTE: some scenes with clouds still is being rendered incorrectly, but this issue can be reproduced with RPR 1. The cause of this issue is 3D textures from Maya which we can't get. Arnold use undocumented way to get these textures

2021-09-09 06:55 UTC, Vsevolod1983 approved these changes

2021-09-09 10:40 UTC, DMotorygin requested changes

2021-09-09 10:40 UTC, DMotorygin commented on FireRender.Maya.Src/FireRenderVolume.cpp
> +	if (vdata.densityGrid.IsValid() && vdata.densityGrid.gridOnIndices.size() > 0) // grid exists
Please consider moving check gridOnIndices.size() > 0 to IsValid() method.

If I understood correctly grid with gridOnIndices.size() == 0 would be invalid, right?

2021-09-09 10:40 UTC, DMotorygin commented on FireRender.Maya.Src/FireRenderVolume.cpp
> +		float maxDensityValue = RPRVolumeAttributes::GetDensityMultiplier(depNode) * 1.1f;
Please make 1.1f multipler a constant and add a comment where 1.1 value comes from

2021-09-09 10:40 UTC, DMotorygin commented on FireRender.Maya.Src/FireRenderVolume.cpp
> +	if (vdata.albedoGrid.IsValid() && vdata.albedoGrid.gridOnIndices.size() > 0) // grid exists
Please consider moving check gridOnIndices.size() > 0 to IsValid() method.

If I understood correctly grid with gridOnIndices.size() == 0 would be invalid, right?

2021-09-09 10:40 UTC, DMotorygin commented on FireRender.Maya.Src/FireRenderVolume.cpp
> +	if (vdata.emissionGrid.IsValid() && vdata.emissionGrid.gridOnIndices.size() > 0) // grid exists
Please consider moving check gridOnIndices.size() > 0 to IsValid() method.

If I understood correctly grid with gridOnIndices.size() == 0 would be invalid, right?

2021-09-09 10:40 UTC, DMotorygin commented on FireRender.Maya.Src/FireRenderVolume.cpp
> +	volumeShader.xSetParameterF(RPR_MATERIAL_INPUT_DENSITY, 1000.f, 1.f, 1.f, 1.f); // multiplication coefficient
Why do we still need a 1000 constant multiplier if we modify grid values directly?

If yes, it was 10 000 in previous version. Was this change intentional?

2021-09-12 13:56 UTC, DMotorygin approved these changes

2021-09-13 20:39 UTC, merged