Referenced materials fix
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #243
Opened 2021-09-08 12:06 UTC by DMotorygin

JIRA TICKET: RPRMAYA-2882, RPRMAYA-2908

PURPOSE: Material in referenced objects rendered as expected, no "multiple uv sets" error appearing

2021-09-09 09:39 UTC, Vsevolod1983 requested changes

2021-09-09 09:39 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderObjects.cpp
> +#ifdef MESH_RELOAD_REFERENCE_DEBUG
please remove this debug code under MESH_RELOAD_REFERENCE_DEBUG in all occurrences
you can make some utility code in FireRenderUtils which opens logginfFile, writes some output passed as a param and close it.

2021-09-09 20:17 UTC, V-Gorash approved these changes

2021-09-13 07:04 UTC, Vsevolod1983 approved these changes

2021-09-15 16:09 UTC, merged