RPRS_context support
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #248
Opened 2021-09-19 17:04 UTC by DMotorygin

JIRA TICKET: RPRMAYA-2877

PURPOSE: Requested by Atsushi Yoshimura

2021-09-20 08:44 UTC, Vsevolod1983 requested changes

2021-09-20 08:44 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderExportCmd.cpp
> +				if (rprsContext != nullptr)
please consider using context from frwrap to make it destroyed automatically. Problem will happen if exception will be thrown. In this case context will not be destroyed

2021-09-21 08:25 UTC, V-Gorash approved these changes

2021-09-23 07:25 UTC, Vsevolod1983 approved these changes

2021-09-24 22:21 UTC, merged