Core 2.2.14 features
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #319
Opened 2022-06-23 13:20 UTC by V-Gorash

JIRA TICKET: RPRMAYA-3181

EFFECT OF CHANGES: 1) New AOV MattePass
2) New parameter: display IBL
3) new mechanism of shadow catcher and reflection catcher

2022-06-23 21:20 UTC, DMotorygin approved these changes

2022-07-06 18:47 UTC, Vsevolod1983 requested changes

2022-07-06 18:47 UTC, Vsevolod1983 commented on .gitmodules
> +	url = git@github.com:V-Gorash/RadeonProRenderSharedComponents.git
Do you plan to discard this change ?

2022-07-12 08:15 UTC, Vsevolod1983 approved these changes

2022-07-15 18:05 UTC, merged