Fix viewport not updating when denoiser enabled
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #359
Opened 2023-01-27 12:33 UTC by DMotorygin

JIRA TICKET: RPRMAYA-3266

PURPOSE: Currently when denoiser and/or tonemapper is enabled in viewport render it is not updated correctly after first render

EFFECT FOR THE USER: Viewport render working as expected

NOTE FOR REVIEWERS: Also updated some debug dump functions in this PR

2023-01-30 13:39 UTC, Vsevolod1983 requested changes

2023-01-30 13:39 UTC, Vsevolod1983 commented on FireRender.Maya.Src/Context/FireRenderContext.cpp
> +	const std::string pathToFile = "C://debug//fb//";
please remove

2023-01-30 13:39 UTC, Vsevolod1983 commented on FireRender.Maya.Src/Context/FireRenderContext.cpp
> +				std::string("RPR_AOV_COLOR"), pathToFile);
Pls remove "pathToFile"if we should not have it here in release mode

2023-01-30 13:39 UTC, Vsevolod1983 commented on FireRender.Maya.Src/Context/FireRenderContext.cpp
> +				std::string("RPR_AOV_SHADING_NORMAL"), pathToFile);
same

2023-01-30 17:09 UTC, Vsevolod1983 approved these changes

2023-02-02 10:13 UTC, DavidSpeicher commented
QA approved

2023-02-02 21:58 UTC, merged