Change default color for albedo to gray
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #364
Opened 2023-02-20 14:43 UTC by Licoman256

JIRA TICKET: RPRMAYA-3299

PURPOSE: Albedo value works as the ratio between scattering and emission, so if setting albedo color to black, only emission (absorption) happens. and if setting it to white, only scattering happens (emission color is not shown). Gray allows both to apply.

EFFECT FOR THE USER: Default albedo gradient goes from gray to white instead of black to white.

2023-02-22 13:56 UTC, DavidSpeicher commented
QA approved

2023-02-22 17:41 UTC, DMotorygin requested changes

2023-02-22 17:41 UTC, DMotorygin commented on FireRender.Maya.Src/FireRenderUtils.h
> +	if (!length)
please change to comparison with zero

2023-02-23 14:03 UTC, DMotorygin approved these changes

2023-02-23 16:10 UTC, merged