Fix black points not saving correctly with ramps and randomly adding different colors when opening a scene
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #368
Opened 2023-03-08 10:36 UTC by Licoman256

JIRA TICKET: RPRMAYA-3312

PURPOSE: Ramps don't save black point correctly, sometimes add default points or change color of points. This PR fixes this. RPRRamp, Albedo, Emission and Density ramps are affected.

EFFECT FOR THE USER: Points on ramps behave as expected.

2023-03-10 15:37 UTC, DavidSpeicher commented
QA Approved

2023-03-13 17:12 UTC, Vsevolod1983 requested changes

2023-03-13 17:12 UTC, Vsevolod1983 commented on FireRender.Maya.Src/scripts/common.mel
> +global proc AERPRCreateDefaultRampColors( string $nodeName, string $colorSrcString, string $posSrcString, string $rampName)
Is it possible to refactor in order to remove code duplicate in this function and same for Floats?

2023-03-13 17:12 UTC, Vsevolod1983 commented on FireRender.Maya.Src/scripts/AERPRVolumeTemplate.mel
> +	string $albedoRampName	    = "|albedoRamp";
Did not get why you add "|" here, could you please explain ?

2023-03-13 17:12 UTC, Vsevolod1983 commented on FireRender.Maya.Src/scripts/common.mel
> +	if($pos      != 0 ||
Should it be "0.0" instead of "0" since its float type for better reading ?

2023-03-13 17:12 UTC, Vsevolod1983 commented on FireRender.Maya.Src/scripts/common.mel
> +		 // bool
pls remove the comment

2023-03-13 18:37 UTC, DMotorygin commented on FireRender.Maya.Src/scripts/common.mel
> +}
Please add extra line

2023-03-17 14:09 UTC, DMotorygin approved these changes

2023-03-30 21:32 UTC, merged