Fix IBL not rendering when exporting a scene
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #369
Opened 2023-03-13 11:38 UTC by Licoman256

JIRA TICKET: RPRMAYA-3314

PURPOSE: IBL does not get exported correctly, always shows up as black. This PR fixes this

EFFECT FOR THE USER: IBL is now exported as expected, does not become black

2023-04-21 10:11 UTC, DavidSpeicher commented
not approved

2023-04-25 14:35 UTC, DMotorygin requested changes

2023-04-25 14:35 UTC, DMotorygin commented on FireRender.Maya.Src/FireRenderObjects.cpp
> -			if (!GetPlugValue("display", true) || m.light.IsAmbientLight())
Why check for "display" flag was removed?

Looks like it would change the logic for override creation

2023-04-25 14:35 UTC, DMotorygin commented on FireRender.Maya.Src/FireRenderShadowCatcherMaterial.cpp
> -		{ &Attribute::bgIsEnv, "bgIsEnv", "bgie", 0, 0, 1, MFnNumericData::kBoolean },
Why setting this parameter was removed?

2023-05-03 13:06 UTC, DMotorygin approved these changes

2023-05-11 10:00 UTC, DavidSpeicher commented
QA Approved

2023-05-12 20:13 UTC, merged