Toon shader UI rework
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #370
Opened 2023-03-20 15:23 UTC by DMotorygin

JIRA TICKET: RPRMAYA-3245

PURPOSE: Change of Toon Shader UI was requested by TMS

EFFECT FOR THE USER: several parameters (9) of Toon Shader that were set by sliders are now set by ramp. Necessary features for such UI were added.

2023-03-23 15:20 UTC, Vsevolod1983 commented on FireRender.Maya.Src/scripts/AERPRToonMaterialTemplate.mel
> +								-at $nodeAttr
a bit weird code alignment

2023-03-23 15:23 UTC, Vsevolod1983 commented on FireRender.Maya.Src/scripts/AERPRToonMaterialTemplate.mel
> +								-at $nodeAttr
its a mix of spaces and tabs all along the file

2023-03-23 15:24 UTC, Vsevolod1983 requested changes
pls fix tabs vs spaces problem in the mel file

2023-03-27 09:01 UTC, Vsevolod1983 approved these changes

2023-03-28 14:16 UTC, DavidSpeicher commented
QA approved

2023-03-28 22:39 UTC, merged