Fix AOVs not enabling when shadow/reflection catcher is enabled in a scene with a referenced object
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #397
Opened 2023-08-28 09:11 UTC by Licoman256

JIRA TICKET: RPRMAYA-3383

PURPOSE: AOVs are not being enabled when shadow/reflection catcher is enabled in a scene with a referenced object. This PR fixes that.

EFFECT FOR THE USER: AOVs are now being enabled as expected when shadow/reflection catcher is enabled in a scene with a referenced object.

2023-08-28 15:09 UTC, DMotorygin requested changes

2023-08-28 15:09 UTC, DMotorygin commented on FireRender.Maya.Src/pluginMain.cpp
> +	MStatus status = MGlobal::executeCommand(melCommand);
Please add MStatus check, e.g. :
assert(status == MStatus::kSuccess);

2023-08-30 16:11 UTC, DMotorygin approved these changes

2023-08-30 19:20 UTC, bsavery approved these changes

2023-08-30 19:24 UTC, merged