Fix tile to file
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #403
Opened 2023-09-11 20:15 UTC by DMotorygin

JIRA TICKET: RPRMAYA-1093

PURPOSE: Make tile render correctly use save to file feature

EFFECT FOR THE USER: User can now see AOVs for full image rendered via tile rendering saved in file, just like with regular render.

NOTE: Thought its related to Hybrid RC5 but turned out to be other issue entirely

2023-09-13 10:19 UTC, DavidSpeicher commented
approved

2023-09-15 14:27 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderCmd.cpp
> +				//// - replace '\' with '/'
do we need these comments ?

2023-09-15 14:27 UTC, Vsevolod1983 requested changes
remove some comments pls if not needed

2023-09-15 14:27 UTC, Vsevolod1983 commented on FireRender.Maya.Src/FireRenderProduction.cpp
> +	//outBuffers.clear();
do we need this comment ?

2023-09-15 14:44 UTC, Vsevolod1983 approved these changes

2023-09-15 21:52 UTC, merged