RPR2 optimizations for viewport
GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin pull request #77
Opened 2020-09-22 17:51 UTC by Vsevolod1983

TCIKET: RPRMAYA-2341

PURPOSE:
Workflow is not optimized for usage of RPR2

EFFECT OF CHANGES:
Workflow is optimized for usage of RPR2
 - Render Callbacks
 - Multithreading processing

2020-09-25 13:48 UTC, bsavery requested changes
Not a functional change, but please add a bit more detail to the effect description, do you want to wait for a review from @DMotorygin ?

2020-09-28 07:17 UTC, Vsevolod1983 commented
He had a vacation, but he is back fron today, so assigned

2020-09-30 18:12 UTC, Vsevolod1983 commented on FireRender.Maya.Src/NorthStarRenderingHelper.cpp
> +	/*if (m_contextPtr->GetSamplesPerUpdate() == 1)
Done

2020-09-30 18:12 UTC, Vsevolod1983 commented on FireRender.Maya.Src/NorthStarRenderingHelper.cpp
> +			std::this_thread::sleep_for(1ms);
Done

2020-09-30 18:24 UTC, DMotorygin commented on FireRender.Maya.Src/NorthStarRenderingHelper.cpp
> +		/*while (!m_DataReady && m_UpdateThreadRunning)
Please remove commented out code

2020-09-30 18:24 UTC, DMotorygin commented on FireRender.Maya.Src/Context/TahoeContext.cpp
> +}
Please add new line at the end of file

2020-10-01 09:40 UTC, Vsevolod1983 commented on FireRender.Maya.Src/NorthStarRenderingHelper.cpp
> +		/*while (!m_DataReady && m_UpdateThreadRunning)
Done

2020-10-01 09:40 UTC, Vsevolod1983 commented on FireRender.Maya.Src/Context/TahoeContext.cpp
> +}
Done

2020-10-01 12:17 UTC, DMotorygin approved these changes

2020-10-02 01:59 UTC, merged